env:
  dir: ./chapter_11/flash-chat-flutter
  artifact-name: chapter-11
  APP_DIR: ./chapter_11/flash-chat-flutter
on:
  push:
    paths:
      - "chapter_11/flash-chat-flutter/**"
name: Chapter-11 Release
jobs:
  chapter-11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: "dev" or "beta"
      # - name: Setup envs
      #   run: |
      #     'echo "$GOOGLE_ANDROID_CONFIG" > /home/runner/work/flutter-bootcamp/flutter-bootcamp/chapter_11/flash-chat-flutter/android/app/google-services.json'
      #     'echo "$GOOGLE_IOS_CONFIG" > /home/runner/work/flutter-bootcamp/flutter-bootcamp/chapter_11/flash-chat-flutter/ios/Runner/GoogleService-Info.plist'
      #   with:
      #     GOOGLE_ANDROID_CONFIG: ${{ secrets.GOOGLE_ANDROID_JSON }}
      #     GOOGLE_IOS_CONFIG: ${{ secrets.GOOGLE_IOS_PLIST }}
      - run: flutter pub get
        working-directory: ${{ env.dir }}
      # - run: flutter build apk
      #   working-directory: ${{ env.dir }}
      # - name: Create a Release APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: ${{env.artifact-name}}
      #     path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk
