on: push
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    env:
      working-directory: ./chapter_1/im_a_coder
    steps:      
    - uses: actions/checkout@v1
    
    - uses: steebchen/flutter@v1.0.0
    - name: install dependencies
      run: flutter pub get
      working-directory: ${{env.working-directory}} 

    #- name: run tests
    #  run: flutter test
    #  working-directory: ${{env.working-directory}} 

    - name: build apk
      run: flutter build apk --release      
      working-directory: ${{env.working-directory}} 

