on: push
name: Test, Build and Release apk
jobs:
  chapter-1:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_1/im_a_coder
      artifact-name: chapter-1
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      #- run: flutter test
      #  working-directory: ./chapter_1/im_a_coder
      - run: flutter build apk
        working-directory: ${{env.dir}}

      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-2:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_2/mi_card_farter
      artifact-name: chapter-2
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      # - run: flutter build apk
      #   working-directory: ${{env.dir}}
      # - name: Create a Release APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: ${{env.artifact-name}}
      #     path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-3:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_3/dicee-flutter
      artifact-name: chapter-3
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      - run: flutter build apk
        working-directory: ${{env.dir}}
      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-4:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_4/magic-8-ball-flutter
      artifact-name: chapter-4
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      - run: flutter build apk
        working-directory: ${{env.dir}}
      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-5:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_5/xylophone-flutter
      artifact-name: chapter-5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      - run: flutter build apk
        working-directory: ${{env.dir}}
      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-6:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_6/quizzler-flutter
      artifact-name: chapter-6
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      - run: flutter build apk
        working-directory: ${{env.dir}}
      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-7:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_7/destini-challenge-starting
      artifact-name: chapter-7
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      - run: flutter build apk
        working-directory: ${{env.dir}}
      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-8:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_8/bmi-calculator-flutter
      artifact-name: chapter-8
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      - run: flutter build apk
        working-directory: ${{env.dir}}
      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-9:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_9/Clima-Flutter
      artifact-name: chapter-9
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      - run: flutter build apk
        working-directory: ${{env.dir}}
      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-10:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_10/bitcoin-ticker-flutter
      artifact-name: chapter-10
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      - run: flutter build apk
        working-directory: ${{env.dir}}
      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

  chapter-11:
    runs-on: ubuntu-latest
    env:
      dir: ./chapter_11/flash-chat-flutter
      artifact-name: chapter-11
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: ${{env.dir}}
      - run: flutter build apk
        working-directory: ${{env.dir}}
      - name: Create a Release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.artifact-name}}
          path: ${{env.dir}}/build/app/outputs/apk/release/app-release.apk

